package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const themeSuffix = ".prompto.yaml"

func main() {
	repoRoot, err := repoRoot()
	if err != nil {
		fail(err)
	}

	themeDirectory := filepath.Join(repoRoot, "themes")
	outputPath := filepath.Join(repoRoot, "src", "themes", "bundled_gen.go")

	entries, err := os.ReadDir(themeDirectory)
	if err != nil {
		fail(err)
	}

	type themeFile struct {
		name    string
		content string
	}

	var themeFiles []themeFile
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if !strings.HasSuffix(entry.Name(), themeSuffix) {
			continue
		}

		fullPath := filepath.Join(themeDirectory, entry.Name())
		content, err := os.ReadFile(fullPath)
		if err != nil {
			fail(err)
		}

		themeFiles = append(themeFiles, themeFile{
			name:    strings.TrimSuffix(entry.Name(), themeSuffix),
			content: string(content),
		})
	}

	sort.Slice(themeFiles, func(i, j int) bool {
		return themeFiles[i].name < themeFiles[j].name
	})

	var output bytes.Buffer
	output.WriteString("// Code generated by src/tools/genthemes; DO NOT EDIT.\n")
	output.WriteString("package themes\n\n")
	output.WriteString("var bundledThemes = map[string]string{\n")
	for _, theme := range themeFiles {
		output.WriteString("\t")
		output.WriteString(strconv.Quote(theme.name))
		output.WriteString(": ")
		output.WriteString(strconv.Quote(theme.content))
		output.WriteString(",\n")
	}
	output.WriteString("}\n")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(outputPath, formatted, 0o644)
	if err != nil {
		fail(err)
	}
}

func repoRoot() (string, error) {
	workingDirectory, err := os.Getwd()
	if err != nil {
		return "", err
	}

	return filepath.Clean(filepath.Join(workingDirectory, "..", "..")), nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
