package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const (
	themeSuffix = ".prompto.yaml"
	// consoleInfix marks a theme's console variant: polo.console.prompto.yaml
	// is the console counterpart of polo.prompto.yaml. Variants are bundled
	// under their base theme's name rather than as themes of their own.
	consoleInfix = ".console"
)

type themeFile struct {
	name    string
	content string
}

func main() {
	repoRoot, err := repoRoot()
	if err != nil {
		fail(err)
	}

	themeDirectory := filepath.Join(repoRoot, "themes")
	outputPath := filepath.Join(repoRoot, "src", "themes", "bundled_gen.go")

	entries, err := os.ReadDir(themeDirectory)
	if err != nil {
		fail(err)
	}

	var themeFiles, consoleFiles []themeFile
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if !strings.HasSuffix(entry.Name(), themeSuffix) {
			continue
		}

		fullPath := filepath.Join(themeDirectory, entry.Name())
		content, err := os.ReadFile(fullPath)
		if err != nil {
			fail(err)
		}

		file := themeFile{
			name:    strings.TrimSuffix(entry.Name(), themeSuffix),
			content: string(content),
		}

		if base, ok := strings.CutSuffix(file.name, consoleInfix); ok {
			file.name = base
			consoleFiles = append(consoleFiles, file)
			continue
		}

		themeFiles = append(themeFiles, file)
	}

	byName := func(files []themeFile) {
		sort.Slice(files, func(i, j int) bool {
			return files[i].name < files[j].name
		})
	}

	byName(themeFiles)
	byName(consoleFiles)

	// A console variant with no base theme can never be reached by name, so it
	// is a packaging mistake rather than something to bundle silently.
	known := make(map[string]bool, len(themeFiles))
	for _, theme := range themeFiles {
		known[theme.name] = true
	}

	for _, variant := range consoleFiles {
		if known[variant.name] {
			continue
		}

		fail(fmt.Errorf("console variant %s%s%s has no matching %s%s", variant.name, consoleInfix, themeSuffix, variant.name, themeSuffix))
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by src/tools/genthemes; DO NOT EDIT.\n")
	output.WriteString("package themes\n\n")
	writeMap(&output, "bundledThemes", themeFiles)
	output.WriteString("\n")
	writeMap(&output, "bundledConsoleThemes", consoleFiles)

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		fail(err)
	}

	err = os.WriteFile(outputPath, formatted, 0o644)
	if err != nil {
		fail(err)
	}
}

func writeMap(output *bytes.Buffer, name string, files []themeFile) {
	fmt.Fprintf(output, "var %s = map[string]string{\n", name)

	for _, file := range files {
		output.WriteString("\t")
		output.WriteString(strconv.Quote(file.name))
		output.WriteString(": ")
		output.WriteString(strconv.Quote(file.content))
		output.WriteString(",\n")
	}

	output.WriteString("}\n")
}

func repoRoot() (string, error) {
	workingDirectory, err := os.Getwd()
	if err != nil {
		return "", err
	}

	return filepath.Clean(filepath.Join(workingDirectory, "..", "..")), nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
