// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: daemon.proto

package ipc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_RenderPrompt_FullMethodName  = "/ipc.DaemonService/RenderPrompt"
	DaemonService_ToggleSegment_FullMethodName = "/ipc.DaemonService/ToggleSegment"
	DaemonService_CacheClear_FullMethodName    = "/ipc.DaemonService/CacheClear"
	DaemonService_CacheSetTTL_FullMethodName   = "/ipc.DaemonService/CacheSetTTL"
	DaemonService_CacheGetTTL_FullMethodName   = "/ipc.DaemonService/CacheGetTTL"
	DaemonService_CacheShow_FullMethodName     = "/ipc.DaemonService/CacheShow"
	DaemonService_SetLogging_FullMethodName    = "/ipc.DaemonService/SetLogging"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DaemonService handles prompt rendering requests.
type DaemonServiceClient interface {
	// RenderPrompt streams segment updates as they complete.
	//
	// Cancellation: a new request for the same session supersedes any
	// in-progress render. The `repaint` field on PromptRequest selects which
	// kind of cancel:
	//   - repaint=false (Hard cancel): on-disk state may have changed — the
	//     prior render's context is aborted; its in-flight computations must
	//     not write to the cache. A fresh render starts.
	//   - repaint=true  (Soft cancel): only the view changed (vim toggle) —
	//     the prior render's computations are preserved; the new request
	//     reattaches to them and reuses their results.
	//
	// See src/daemon/ARCHITECTURE.md ("The cancel model") for details.
	RenderPrompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PromptResponse], error)
	// ToggleSegment toggles the visibility of segments for a session.
	ToggleSegment(ctx context.Context, in *ToggleSegmentRequest, opts ...grpc.CallOption) (*ToggleSegmentResponse, error)
	// CacheClear clears all daemon cache entries.
	CacheClear(ctx context.Context, in *CacheClearRequest, opts ...grpc.CallOption) (*CacheClearResponse, error)
	// CacheSetTTL sets the default cache TTL (in days).
	CacheSetTTL(ctx context.Context, in *CacheSetTTLRequest, opts ...grpc.CallOption) (*CacheSetTTLResponse, error)
	// CacheGetTTL gets the current default cache TTL (in days).
	CacheGetTTL(ctx context.Context, in *CacheGetTTLRequest, opts ...grpc.CallOption) (*CacheGetTTLResponse, error)
	// CacheShow retrieves daemon cache entries grouped by scope.
	CacheShow(ctx context.Context, in *CacheShowRequest, opts ...grpc.CallOption) (*CacheShowResponse, error)
	// SetLogging enables or disables file logging on the running daemon.
	SetLogging(ctx context.Context, in *SetLoggingRequest, opts ...grpc.CallOption) (*SetLoggingResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) RenderPrompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PromptResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[0], DaemonService_RenderPrompt_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PromptRequest, PromptResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_RenderPromptClient = grpc.ServerStreamingClient[PromptResponse]

func (c *daemonServiceClient) ToggleSegment(ctx context.Context, in *ToggleSegmentRequest, opts ...grpc.CallOption) (*ToggleSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToggleSegmentResponse)
	err := c.cc.Invoke(ctx, DaemonService_ToggleSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CacheClear(ctx context.Context, in *CacheClearRequest, opts ...grpc.CallOption) (*CacheClearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheClearResponse)
	err := c.cc.Invoke(ctx, DaemonService_CacheClear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CacheSetTTL(ctx context.Context, in *CacheSetTTLRequest, opts ...grpc.CallOption) (*CacheSetTTLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheSetTTLResponse)
	err := c.cc.Invoke(ctx, DaemonService_CacheSetTTL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CacheGetTTL(ctx context.Context, in *CacheGetTTLRequest, opts ...grpc.CallOption) (*CacheGetTTLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheGetTTLResponse)
	err := c.cc.Invoke(ctx, DaemonService_CacheGetTTL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CacheShow(ctx context.Context, in *CacheShowRequest, opts ...grpc.CallOption) (*CacheShowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CacheShowResponse)
	err := c.cc.Invoke(ctx, DaemonService_CacheShow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) SetLogging(ctx context.Context, in *SetLoggingRequest, opts ...grpc.CallOption) (*SetLoggingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLoggingResponse)
	err := c.cc.Invoke(ctx, DaemonService_SetLogging_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
//
// DaemonService handles prompt rendering requests.
type DaemonServiceServer interface {
	// RenderPrompt streams segment updates as they complete.
	//
	// Cancellation: a new request for the same session supersedes any
	// in-progress render. The `repaint` field on PromptRequest selects which
	// kind of cancel:
	//   - repaint=false (Hard cancel): on-disk state may have changed — the
	//     prior render's context is aborted; its in-flight computations must
	//     not write to the cache. A fresh render starts.
	//   - repaint=true  (Soft cancel): only the view changed (vim toggle) —
	//     the prior render's computations are preserved; the new request
	//     reattaches to them and reuses their results.
	//
	// See src/daemon/ARCHITECTURE.md ("The cancel model") for details.
	RenderPrompt(*PromptRequest, grpc.ServerStreamingServer[PromptResponse]) error
	// ToggleSegment toggles the visibility of segments for a session.
	ToggleSegment(context.Context, *ToggleSegmentRequest) (*ToggleSegmentResponse, error)
	// CacheClear clears all daemon cache entries.
	CacheClear(context.Context, *CacheClearRequest) (*CacheClearResponse, error)
	// CacheSetTTL sets the default cache TTL (in days).
	CacheSetTTL(context.Context, *CacheSetTTLRequest) (*CacheSetTTLResponse, error)
	// CacheGetTTL gets the current default cache TTL (in days).
	CacheGetTTL(context.Context, *CacheGetTTLRequest) (*CacheGetTTLResponse, error)
	// CacheShow retrieves daemon cache entries grouped by scope.
	CacheShow(context.Context, *CacheShowRequest) (*CacheShowResponse, error)
	// SetLogging enables or disables file logging on the running daemon.
	SetLogging(context.Context, *SetLoggingRequest) (*SetLoggingResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) RenderPrompt(*PromptRequest, grpc.ServerStreamingServer[PromptResponse]) error {
	return status.Error(codes.Unimplemented, "method RenderPrompt not implemented")
}
func (UnimplementedDaemonServiceServer) ToggleSegment(context.Context, *ToggleSegmentRequest) (*ToggleSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleSegment not implemented")
}
func (UnimplementedDaemonServiceServer) CacheClear(context.Context, *CacheClearRequest) (*CacheClearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CacheClear not implemented")
}
func (UnimplementedDaemonServiceServer) CacheSetTTL(context.Context, *CacheSetTTLRequest) (*CacheSetTTLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CacheSetTTL not implemented")
}
func (UnimplementedDaemonServiceServer) CacheGetTTL(context.Context, *CacheGetTTLRequest) (*CacheGetTTLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CacheGetTTL not implemented")
}
func (UnimplementedDaemonServiceServer) CacheShow(context.Context, *CacheShowRequest) (*CacheShowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CacheShow not implemented")
}
func (UnimplementedDaemonServiceServer) SetLogging(context.Context, *SetLoggingRequest) (*SetLoggingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLogging not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_RenderPrompt_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PromptRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).RenderPrompt(m, &grpc.GenericServerStream[PromptRequest, PromptResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_RenderPromptServer = grpc.ServerStreamingServer[PromptResponse]

func _DaemonService_ToggleSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ToggleSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ToggleSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ToggleSegment(ctx, req.(*ToggleSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CacheClear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CacheClear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CacheClear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CacheClear(ctx, req.(*CacheClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CacheSetTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheSetTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CacheSetTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CacheSetTTL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CacheSetTTL(ctx, req.(*CacheSetTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CacheGetTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheGetTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CacheGetTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CacheGetTTL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CacheGetTTL(ctx, req.(*CacheGetTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CacheShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CacheShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CacheShow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CacheShow(ctx, req.(*CacheShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_SetLogging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLoggingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).SetLogging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_SetLogging_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).SetLogging(ctx, req.(*SetLoggingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ipc.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ToggleSegment",
			Handler:    _DaemonService_ToggleSegment_Handler,
		},
		{
			MethodName: "CacheClear",
			Handler:    _DaemonService_CacheClear_Handler,
		},
		{
			MethodName: "CacheSetTTL",
			Handler:    _DaemonService_CacheSetTTL_Handler,
		},
		{
			MethodName: "CacheGetTTL",
			Handler:    _DaemonService_CacheGetTTL_Handler,
		},
		{
			MethodName: "CacheShow",
			Handler:    _DaemonService_CacheShow_Handler,
		},
		{
			MethodName: "SetLogging",
			Handler:    _DaemonService_SetLogging_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RenderPrompt",
			Handler:       _DaemonService_RenderPrompt_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "daemon.proto",
}
