// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: daemon.proto

package ipc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToggleSegmentRequest contains segments to toggle.
type ToggleSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Segments      []string               `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleSegmentRequest) Reset() {
	*x = ToggleSegmentRequest{}
	mi := &file_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleSegmentRequest) ProtoMessage() {}

func (x *ToggleSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleSegmentRequest.ProtoReflect.Descriptor instead.
func (*ToggleSegmentRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *ToggleSegmentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ToggleSegmentRequest) GetSegments() []string {
	if x != nil {
		return x.Segments
	}
	return nil
}

type ToggleSegmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleSegmentResponse) Reset() {
	*x = ToggleSegmentResponse{}
	mi := &file_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleSegmentResponse) ProtoMessage() {}

func (x *ToggleSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleSegmentResponse.ProtoReflect.Descriptor instead.
func (*ToggleSegmentResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *ToggleSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToggleSegmentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// PromptRequest contains all information needed to render prompts.
type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`                                                                  // Protocol version for evolution
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                                              // Terminal session ID
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                              // Unique request ID for cancellation
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables
	Flags         *Flags                 `protobuf:"bytes,5,opt,name=flags,proto3" json:"flags,omitempty"`                                                                       // Runtime flags
	Pid           int32                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`                                                                          // Shell process ID for session tracking
	Repaint       bool                   `protobuf:"varint,7,opt,name=repaint,proto3" json:"repaint,omitempty"`                                                                  // Soft cancel: vim mode toggle (reuse computations)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *PromptRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PromptRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PromptRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PromptRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *PromptRequest) GetFlags() *Flags {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *PromptRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PromptRequest) GetRepaint() bool {
	if x != nil {
		return x.Repaint
	}
	return false
}

// Flags contains runtime flags passed to the prompt engine.
// Mirrors runtime.Flags from the Go codebase.
type Flags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                           // Prompt type (primary, secondary, etc.)
	PipeStatus    string                 `protobuf:"bytes,2,opt,name=pipe_status,json=pipeStatus,proto3" json:"pipe_status,omitempty"`             // Pipe status codes
	ConfigPath    string                 `protobuf:"bytes,3,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`             // Config file path
	Pswd          string                 `protobuf:"bytes,4,opt,name=pswd,proto3" json:"pswd,omitempty"`                                           // PowerShell working directory
	Shell         string                 `protobuf:"bytes,5,opt,name=shell,proto3" json:"shell,omitempty"`                                         // Shell name
	ShellVersion  string                 `protobuf:"bytes,6,opt,name=shell_version,json=shellVersion,proto3" json:"shell_version,omitempty"`       // Shell version
	Command       string                 `protobuf:"bytes,30,opt,name=command,proto3" json:"command,omitempty"`                                    // Tooltip/auxiliary command context
	Pwd           string                 `protobuf:"bytes,7,opt,name=pwd,proto3" json:"pwd,omitempty"`                                             // Current working directory
	AbsolutePwd   string                 `protobuf:"bytes,8,opt,name=absolute_pwd,json=absolutePwd,proto3" json:"absolute_pwd,omitempty"`          // Absolute working directory
	ErrorCode     int32                  `protobuf:"varint,9,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`               // Exit code of last command
	PromptCount   int32                  `protobuf:"varint,10,opt,name=prompt_count,json=promptCount,proto3" json:"prompt_count,omitempty"`        // Prompt count
	Column        int32                  `protobuf:"varint,11,opt,name=column,proto3" json:"column,omitempty"`                                     // Cursor column position
	TerminalWidth int32                  `protobuf:"varint,12,opt,name=terminal_width,json=terminalWidth,proto3" json:"terminal_width,omitempty"`  // Terminal width
	ExecutionTime float64                `protobuf:"fixed64,13,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"` // Execution time of last command in ms
	StackCount    int32                  `protobuf:"varint,14,opt,name=stack_count,json=stackCount,proto3" json:"stack_count,omitempty"`           // Directory stack count
	ConfigHash    uint64                 `protobuf:"varint,15,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`           // Config hash for cache invalidation
	JobCount      int32                  `protobuf:"varint,16,opt,name=job_count,json=jobCount,proto3" json:"job_count,omitempty"`                 // Background job count
	HasExtra      bool                   `protobuf:"varint,17,opt,name=has_extra,json=hasExtra,proto3" json:"has_extra,omitempty"`                 // Has extra context
	Strict        bool                   `protobuf:"varint,18,opt,name=strict,proto3" json:"strict,omitempty"`                                     // Strict mode
	Debug         bool                   `protobuf:"varint,19,opt,name=debug,proto3" json:"debug,omitempty"`                                       // Debug mode
	Cleared       bool                   `protobuf:"varint,20,opt,name=cleared,proto3" json:"cleared,omitempty"`                                   // Screen was cleared
	NoExitCode    bool                   `protobuf:"varint,21,opt,name=no_exit_code,json=noExitCode,proto3" json:"no_exit_code,omitempty"`         // No valid status code
	Init          bool                   `protobuf:"varint,22,opt,name=init,proto3" json:"init,omitempty"`                                         // Init mode
	Migrate       bool                   `protobuf:"varint,23,opt,name=migrate,proto3" json:"migrate,omitempty"`                                   // Migrate mode
	Eval          bool                   `protobuf:"varint,24,opt,name=eval,proto3" json:"eval,omitempty"`                                         // Eval mode
	Escape        bool                   `protobuf:"varint,25,opt,name=escape,proto3" json:"escape,omitempty"`                                     // Escape ANSI sequences
	IsPrimary     bool                   `protobuf:"varint,26,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`              // Is primary prompt
	Plain         bool                   `protobuf:"varint,27,opt,name=plain,proto3" json:"plain,omitempty"`                                       // Plain text mode
	Force         bool                   `protobuf:"varint,28,opt,name=force,proto3" json:"force,omitempty"`                                       // Force rendering
	VimMode       string                 `protobuf:"bytes,29,opt,name=vim_mode,json=vimMode,proto3" json:"vim_mode,omitempty"`                     // Current vim mode (insert, normal, visual, replace)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flags) Reset() {
	*x = Flags{}
	mi := &file_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flags) ProtoMessage() {}

func (x *Flags) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flags.ProtoReflect.Descriptor instead.
func (*Flags) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *Flags) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Flags) GetPipeStatus() string {
	if x != nil {
		return x.PipeStatus
	}
	return ""
}

func (x *Flags) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *Flags) GetPswd() string {
	if x != nil {
		return x.Pswd
	}
	return ""
}

func (x *Flags) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *Flags) GetShellVersion() string {
	if x != nil {
		return x.ShellVersion
	}
	return ""
}

func (x *Flags) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Flags) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *Flags) GetAbsolutePwd() string {
	if x != nil {
		return x.AbsolutePwd
	}
	return ""
}

func (x *Flags) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *Flags) GetPromptCount() int32 {
	if x != nil {
		return x.PromptCount
	}
	return 0
}

func (x *Flags) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Flags) GetTerminalWidth() int32 {
	if x != nil {
		return x.TerminalWidth
	}
	return 0
}

func (x *Flags) GetExecutionTime() float64 {
	if x != nil {
		return x.ExecutionTime
	}
	return 0
}

func (x *Flags) GetStackCount() int32 {
	if x != nil {
		return x.StackCount
	}
	return 0
}

func (x *Flags) GetConfigHash() uint64 {
	if x != nil {
		return x.ConfigHash
	}
	return 0
}

func (x *Flags) GetJobCount() int32 {
	if x != nil {
		return x.JobCount
	}
	return 0
}

func (x *Flags) GetHasExtra() bool {
	if x != nil {
		return x.HasExtra
	}
	return false
}

func (x *Flags) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

func (x *Flags) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *Flags) GetCleared() bool {
	if x != nil {
		return x.Cleared
	}
	return false
}

func (x *Flags) GetNoExitCode() bool {
	if x != nil {
		return x.NoExitCode
	}
	return false
}

func (x *Flags) GetInit() bool {
	if x != nil {
		return x.Init
	}
	return false
}

func (x *Flags) GetMigrate() bool {
	if x != nil {
		return x.Migrate
	}
	return false
}

func (x *Flags) GetEval() bool {
	if x != nil {
		return x.Eval
	}
	return false
}

func (x *Flags) GetEscape() bool {
	if x != nil {
		return x.Escape
	}
	return false
}

func (x *Flags) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *Flags) GetPlain() bool {
	if x != nil {
		return x.Plain
	}
	return false
}

func (x *Flags) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *Flags) GetVimMode() string {
	if x != nil {
		return x.VimMode
	}
	return ""
}

// PromptResponse contains rendered prompts and segment updates.
type PromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                                                 // "update" or "complete"
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                      // Echo back for cancellation check
	Prompts       map[string]*Prompt     `protobuf:"bytes,3,rep,name=prompts,proto3" json:"prompts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // All prompts: "primary", "right", etc.
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                                                               // Error message if any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptResponse) Reset() {
	*x = PromptResponse{}
	mi := &file_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptResponse) ProtoMessage() {}

func (x *PromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptResponse.ProtoReflect.Descriptor instead.
func (*PromptResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *PromptResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PromptResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PromptResponse) GetPrompts() map[string]*Prompt {
	if x != nil {
		return x.Prompts
	}
	return nil
}

func (x *PromptResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Prompt contains the rendered prompt string.
type Prompt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // Fully rendered prompt (ANSI formatted)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prompt) Reset() {
	*x = Prompt{}
	mi := &file_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prompt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prompt) ProtoMessage() {}

func (x *Prompt) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prompt.ProtoReflect.Descriptor instead.
func (*Prompt) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *Prompt) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// CacheClearRequest requests clearing all daemon cache entries.
type CacheClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheClearRequest) Reset() {
	*x = CacheClearRequest{}
	mi := &file_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheClearRequest) ProtoMessage() {}

func (x *CacheClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheClearRequest.ProtoReflect.Descriptor instead.
func (*CacheClearRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{6}
}

// CacheClearResponse is the response to a cache clear request.
type CacheClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheClearResponse) Reset() {
	*x = CacheClearResponse{}
	mi := &file_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheClearResponse) ProtoMessage() {}

func (x *CacheClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheClearResponse.ProtoReflect.Descriptor instead.
func (*CacheClearResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *CacheClearResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CacheClearResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CacheSetTTLRequest sets the default cache TTL.
type CacheSetTTLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"` // TTL in days
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheSetTTLRequest) Reset() {
	*x = CacheSetTTLRequest{}
	mi := &file_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheSetTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetTTLRequest) ProtoMessage() {}

func (x *CacheSetTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetTTLRequest.ProtoReflect.Descriptor instead.
func (*CacheSetTTLRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *CacheSetTTLRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

// CacheSetTTLResponse is the response to a set TTL request.
type CacheSetTTLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheSetTTLResponse) Reset() {
	*x = CacheSetTTLResponse{}
	mi := &file_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheSetTTLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetTTLResponse) ProtoMessage() {}

func (x *CacheSetTTLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetTTLResponse.ProtoReflect.Descriptor instead.
func (*CacheSetTTLResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *CacheSetTTLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// CacheGetTTLRequest gets the current default cache TTL.
type CacheGetTTLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheGetTTLRequest) Reset() {
	*x = CacheGetTTLRequest{}
	mi := &file_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheGetTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetTTLRequest) ProtoMessage() {}

func (x *CacheGetTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetTTLRequest.ProtoReflect.Descriptor instead.
func (*CacheGetTTLRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{10}
}

// CacheGetTTLResponse returns the current default cache TTL.
type CacheGetTTLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"` // TTL in days
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheGetTTLResponse) Reset() {
	*x = CacheGetTTLResponse{}
	mi := &file_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheGetTTLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetTTLResponse) ProtoMessage() {}

func (x *CacheGetTTLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetTTLResponse.ProtoReflect.Descriptor instead.
func (*CacheGetTTLResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *CacheGetTTLResponse) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

// SetLoggingRequest enables or disables daemon file logging.
type SetLoggingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // File path to log to (empty = disable logging)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoggingRequest) Reset() {
	*x = SetLoggingRequest{}
	mi := &file_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoggingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoggingRequest) ProtoMessage() {}

func (x *SetLoggingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoggingRequest.ProtoReflect.Descriptor instead.
func (*SetLoggingRequest) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *SetLoggingRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// SetLoggingResponse is the response to a set logging request.
type SetLoggingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoggingResponse) Reset() {
	*x = SetLoggingResponse{}
	mi := &file_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoggingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoggingResponse) ProtoMessage() {}

func (x *SetLoggingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoggingResponse.ProtoReflect.Descriptor instead.
func (*SetLoggingResponse) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *SetLoggingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetLoggingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_daemon_proto protoreflect.FileDescriptor

const file_daemon_proto_rawDesc = "" +
	"\n" +
	"\fdaemon.proto\x12\x03ipc\"Q\n" +
	"\x14ToggleSegmentRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsegments\x18\x02 \x03(\tR\bsegments\"G\n" +
	"\x15ToggleSegmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9c\x02\n" +
	"\rPromptRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12-\n" +
	"\x03env\x18\x04 \x03(\v2\x1b.ipc.PromptRequest.EnvEntryR\x03env\x12 \n" +
	"\x05flags\x18\x05 \x01(\v2\n" +
	".ipc.FlagsR\x05flags\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x05R\x03pid\x12\x18\n" +
	"\arepaint\x18\a \x01(\bR\arepaint\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x06\n" +
	"\x05Flags\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vpipe_status\x18\x02 \x01(\tR\n" +
	"pipeStatus\x12\x1f\n" +
	"\vconfig_path\x18\x03 \x01(\tR\n" +
	"configPath\x12\x12\n" +
	"\x04pswd\x18\x04 \x01(\tR\x04pswd\x12\x14\n" +
	"\x05shell\x18\x05 \x01(\tR\x05shell\x12#\n" +
	"\rshell_version\x18\x06 \x01(\tR\fshellVersion\x12\x18\n" +
	"\acommand\x18\x1e \x01(\tR\acommand\x12\x10\n" +
	"\x03pwd\x18\a \x01(\tR\x03pwd\x12!\n" +
	"\fabsolute_pwd\x18\b \x01(\tR\vabsolutePwd\x12\x1d\n" +
	"\n" +
	"error_code\x18\t \x01(\x05R\terrorCode\x12!\n" +
	"\fprompt_count\x18\n" +
	" \x01(\x05R\vpromptCount\x12\x16\n" +
	"\x06column\x18\v \x01(\x05R\x06column\x12%\n" +
	"\x0eterminal_width\x18\f \x01(\x05R\rterminalWidth\x12%\n" +
	"\x0eexecution_time\x18\r \x01(\x01R\rexecutionTime\x12\x1f\n" +
	"\vstack_count\x18\x0e \x01(\x05R\n" +
	"stackCount\x12\x1f\n" +
	"\vconfig_hash\x18\x0f \x01(\x04R\n" +
	"configHash\x12\x1b\n" +
	"\tjob_count\x18\x10 \x01(\x05R\bjobCount\x12\x1b\n" +
	"\thas_extra\x18\x11 \x01(\bR\bhasExtra\x12\x16\n" +
	"\x06strict\x18\x12 \x01(\bR\x06strict\x12\x14\n" +
	"\x05debug\x18\x13 \x01(\bR\x05debug\x12\x18\n" +
	"\acleared\x18\x14 \x01(\bR\acleared\x12 \n" +
	"\fno_exit_code\x18\x15 \x01(\bR\n" +
	"noExitCode\x12\x12\n" +
	"\x04init\x18\x16 \x01(\bR\x04init\x12\x18\n" +
	"\amigrate\x18\x17 \x01(\bR\amigrate\x12\x12\n" +
	"\x04eval\x18\x18 \x01(\bR\x04eval\x12\x16\n" +
	"\x06escape\x18\x19 \x01(\bR\x06escape\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x1a \x01(\bR\tisPrimary\x12\x14\n" +
	"\x05plain\x18\x1b \x01(\bR\x05plain\x12\x14\n" +
	"\x05force\x18\x1c \x01(\bR\x05force\x12\x19\n" +
	"\bvim_mode\x18\x1d \x01(\tR\avimMode\"\xde\x01\n" +
	"\x0ePromptResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12:\n" +
	"\aprompts\x18\x03 \x03(\v2 .ipc.PromptResponse.PromptsEntryR\aprompts\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x1aG\n" +
	"\fPromptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.ipc.PromptR\x05value:\x028\x01\"\x1c\n" +
	"\x06Prompt\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x13\n" +
	"\x11CacheClearRequest\"D\n" +
	"\x12CacheClearResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"(\n" +
	"\x12CacheSetTTLRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"/\n" +
	"\x13CacheSetTTLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12CacheGetTTLRequest\")\n" +
	"\x13CacheGetTTLResponse\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"'\n" +
	"\x11SetLoggingRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"D\n" +
	"\x12SetLoggingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x94\x03\n" +
	"\rDaemonService\x129\n" +
	"\fRenderPrompt\x12\x12.ipc.PromptRequest\x1a\x13.ipc.PromptResponse0\x01\x12F\n" +
	"\rToggleSegment\x12\x19.ipc.ToggleSegmentRequest\x1a\x1a.ipc.ToggleSegmentResponse\x12=\n" +
	"\n" +
	"CacheClear\x12\x16.ipc.CacheClearRequest\x1a\x17.ipc.CacheClearResponse\x12@\n" +
	"\vCacheSetTTL\x12\x17.ipc.CacheSetTTLRequest\x1a\x18.ipc.CacheSetTTLResponse\x12@\n" +
	"\vCacheGetTTL\x12\x17.ipc.CacheGetTTLRequest\x1a\x18.ipc.CacheGetTTLResponse\x12=\n" +
	"\n" +
	"SetLogging\x12\x16.ipc.SetLoggingRequest\x1a\x17.ipc.SetLoggingResponseB(Z&github.com/po1o/prompto/src/daemon/ipcb\x06proto3"

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData []byte
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)))
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_daemon_proto_goTypes = []any{
	(*ToggleSegmentRequest)(nil),  // 0: ipc.ToggleSegmentRequest
	(*ToggleSegmentResponse)(nil), // 1: ipc.ToggleSegmentResponse
	(*PromptRequest)(nil),         // 2: ipc.PromptRequest
	(*Flags)(nil),                 // 3: ipc.Flags
	(*PromptResponse)(nil),        // 4: ipc.PromptResponse
	(*Prompt)(nil),                // 5: ipc.Prompt
	(*CacheClearRequest)(nil),     // 6: ipc.CacheClearRequest
	(*CacheClearResponse)(nil),    // 7: ipc.CacheClearResponse
	(*CacheSetTTLRequest)(nil),    // 8: ipc.CacheSetTTLRequest
	(*CacheSetTTLResponse)(nil),   // 9: ipc.CacheSetTTLResponse
	(*CacheGetTTLRequest)(nil),    // 10: ipc.CacheGetTTLRequest
	(*CacheGetTTLResponse)(nil),   // 11: ipc.CacheGetTTLResponse
	(*SetLoggingRequest)(nil),     // 12: ipc.SetLoggingRequest
	(*SetLoggingResponse)(nil),    // 13: ipc.SetLoggingResponse
	nil,                           // 14: ipc.PromptRequest.EnvEntry
	nil,                           // 15: ipc.PromptResponse.PromptsEntry
}
var file_daemon_proto_depIdxs = []int32{
	14, // 0: ipc.PromptRequest.env:type_name -> ipc.PromptRequest.EnvEntry
	3,  // 1: ipc.PromptRequest.flags:type_name -> ipc.Flags
	15, // 2: ipc.PromptResponse.prompts:type_name -> ipc.PromptResponse.PromptsEntry
	5,  // 3: ipc.PromptResponse.PromptsEntry.value:type_name -> ipc.Prompt
	2,  // 4: ipc.DaemonService.RenderPrompt:input_type -> ipc.PromptRequest
	0,  // 5: ipc.DaemonService.ToggleSegment:input_type -> ipc.ToggleSegmentRequest
	6,  // 6: ipc.DaemonService.CacheClear:input_type -> ipc.CacheClearRequest
	8,  // 7: ipc.DaemonService.CacheSetTTL:input_type -> ipc.CacheSetTTLRequest
	10, // 8: ipc.DaemonService.CacheGetTTL:input_type -> ipc.CacheGetTTLRequest
	12, // 9: ipc.DaemonService.SetLogging:input_type -> ipc.SetLoggingRequest
	4,  // 10: ipc.DaemonService.RenderPrompt:output_type -> ipc.PromptResponse
	1,  // 11: ipc.DaemonService.ToggleSegment:output_type -> ipc.ToggleSegmentResponse
	7,  // 12: ipc.DaemonService.CacheClear:output_type -> ipc.CacheClearResponse
	9,  // 13: ipc.DaemonService.CacheSetTTL:output_type -> ipc.CacheSetTTLResponse
	11, // 14: ipc.DaemonService.CacheGetTTL:output_type -> ipc.CacheGetTTLResponse
	13, // 15: ipc.DaemonService.SetLogging:output_type -> ipc.SetLoggingResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
