blank_issues_enabled: false
contact_links:
  - name: Prompto FAQ
    url: https://prompto.dev/docs/faq
    about: Please find common issues here.
  - name: Prompto Docs
    url: https://prompto.dev/docs
    about: RTFM
  - name: Prompto Q&A
    url: https://github.com/po1o/prompto/discussions
    about: Please ask questions here.
