# Make sure to check the documentation at https://goreleaser.com
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
builds:
  -
    binary: "prompto-{{ .Os }}-{{ .Arch }}"
    no_unique_dist_dir: true
    flags:
      - -a
    ldflags:
      - -s -w
      - -X github.com/po1o/prompto/src/build.Version={{ .Version }}
      - -X github.com/po1o/prompto/src/build.Date={{ .Date }}
      - -extldflags "-static"
    tags:
      - netgo
      - osusergo
      - static_build
      - timetzdata
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=greenteagc,jsonv2
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
archives:
  - id: prompto
    format: binary
    name_template: "prompto-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
changelog:
  disable: true
