on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'COPYING'
      - '.github/*.md'
      - '.github/FUNDING.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Build Code
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/src
    steps:
    - name: Checkout code 👋
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
    - name: Install Go 🗳
      uses: ./.github/workflows/composite/bootstrap-go
    - name: Install Protobuf 🧬
      uses: ./.github/workflows/composite/bootstrap-protobuf
    - name: Generate Code
      run: go generate ./...
    - name: Verify Generated Code
      run: |
        if ! git diff --exit-code -- .; then
          git --no-pager diff --stat
          echo "generated files are out of date"
          exit 1
        fi
    - name: Golang CI
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20
      with:
        working-directory: src
    - name: Fieldalignment
      run: |
        export PATH="$(go env GOPATH)/bin:$PATH"
        go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
        go list ./... | grep -v '/daemon/ipc$' | xargs fieldalignment
    - name: Modernize
      run: |
        export PATH="$(go env GOPATH)/bin:$PATH"
        go install golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest
        go list ./... | grep -v '/daemon/ipc$' | xargs modernize
    - name: Run GoReleaser 🚀
      uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a
      with:
        distribution: goreleaser
        version: v2.3.2
        args: build --clean --snapshot
        workdir: src
    - name: Archive production artifacts
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
      with:
        name: builds
        retention-days: 1
        path: |
          src/dist
