name: Markdownlint

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
    - name: Lint files
      uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff
      with:
          config: .markdownlint-cli2.yaml
          globs: '**/*.md'
